services:

# # UDP SOCAT 
#   nmea-udp:
#     build: .
#     # image: ghcr.io/rise-maritime/keelson-connector-nmea:latest
#     container_name: keelson-connector-nmea
#     restart: unless-stopped
#     network_mode: "host"
#     command: ["socat UDP4-RECV:8500,reuseaddr STDOUT | main --log-level 10 -r rise -e ssrs18 -s rutx --publish raw"]
    

# USB SOCAT 
  nmea-usb:
    build: .
    # image: ghcr.io/rise-maritime/keelson-connector-nmea:latest
    container_name: keelson-connector-nmea-usb
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    command: ["socat /dev/ttyUSB1,raw,echo=0,b115200 STDOUT | main --log-level 10 -r rise -e ssrs18 -s sealog --publish all"]